### ISSUE TITLE
Bug: Supposedly wrong types in query with filter_fields since 2.4.0

### ISSUE THREAD

**Issue by lassesteffen** [graphql-python/graphene-django#750]
### Problem
When using filter_fields I get an error about using wrong types which started appearing in 2.4.0.
`Variable "startedAtNull" of type "Boolean" used in position expecting type "DateTime".` The error does not occur with graphene-django 2.3.2

### Context
- using django-filter 2.2.0
- django 2.4.0
### 
**Schema.py**
```
DATETIME_FILTERS = ['exact', 'isnull', 'lt', 'lte', 'gt', 'gte', 'month', 'year', 'date']

class OrderNode(DjangoObjectType):
    class Meta:
        model = Order
        exclude = ('tenant', )
        filter_fields = {
            'id': ['exact'],
            'start_at': DATETIME_FILTERS,
            'finish_at': DATETIME_FILTERS,
            'finished_at': DATETIME_FILTERS,
            'started_at': DATETIME_FILTERS,
        }
        interfaces = (OrderNodeInterface,)
```

**Query:**
```
ORDERS_QUERY = '''
    query order(
        $tenant: String
        $projectId: ID
        $startedAtNull: Boolean
    ) {
        orders(
            tenant: $tenant
            project_Id: $projectId
            startedAt_Isnull: $startedAtNull
        ) {
            edges {
                node {
                    id,
                    city
                }
            }
        }
    }
'''
```

**Result:**
`Variable "startedAtNull" of type "Boolean" used in position expecting type "DateTime".`

### Solution
I am confident it is related to this PR: https://github.com/graphql-python/graphene-django/pull/682/files . In graphene_django/filter/utils.py the way how to retrieve the Type of a field was changed. Or maybe I misunderstood the changelog.

**Comment by jkimbo** [comment]
@lassesteffen does the same issue happen with v2.5.0? It contained a bugfix that looks related: https://github.com/graphql-python/graphene-django/pull/730

**Comment by rangermeier** [comment]
I encounter the same issue after upgrading from 2.3.2 to 2.4.0 or 2.5.0.  The expected type for an `isnull` filter changed from boolean to ID.

Schema:
```class Folder(DjangoObjectType):

    class Meta:
        model = models.Folder
        interfaces = (relay.Node, )
        filter_fields = {
            'parent': ['exact', 'isnull'],
        }
```

Query:
```
{
  user {
    folders(parent_Isnull: true) {
      edges {
        node {
          id
        }
      }
    }
  }
}
```

Result:
```
{
  "errors": [
    {
      "message": "Argument \"parent_Isnull\" has invalid value true.\nExpected type \"ID\", found true.",
      "locations": [
        {
          "line": 8,
          "column": 30
        }
      ]
    }
  ]
}
```

**Comment by jkimbo** [comment]
Hmm ok this looks like a bug, sorry about that. I'll take a look as soon as possible.

**Comment by jkimbo** [comment]
@lassesteffen I've create a PR that should fix this issue: https://github.com/graphql-python/graphene-django/pull/753

**Comment by kikeh** [comment]
@jkimbo I'm still having issues with this, similar to what @lassesteffen is getting, even replicating your PR changes. In my case the message is:
```
Variable "phone" of type "String!" used in position expecting type "ID".
```
If I have time I will try to take a deeper look at this.

**Comment by martasd** [comment]
What's the suggested workaround for this bug? How to create a nullable field in graphql?

**Comment by kikeh** [comment]
@martasd probably the issue with nullable fields is what @jkimbo proposes.

In my case, it was a different problem (similar to what I tried to fix on #730), there are some filters that apply to field lookups, such as: `user__phone__icontains`.

In this case, the _split_ made to the `name` won't work:

```python
name = 'user__phone__icontains'
field_name, filter_type = name.split("__", 1)
# field name = 'user'
# filter_type = 'phone__contains' # which is not right
```

We would need to use `rsplit` instead:

```python
name = 'user__phone__icontains'
field_name, filter_type = name.rsplit("__", 1)
# field name = 'user__phone'
# filter_type = 'contains'
```

This is working fine for me. So @jkimbo, maybe you want to try that out or if you want me to create a PR based on that, it's ok too. Whatever works out better :)

**Comment by jkimbo** [comment]
Good spot @kikeh - I've update the PR now.

Sorry for the delay on this. I've been on holiday and I'm just catching up on things now.

**Comment by martasd** [comment]
Hi. I am still seeing the same issue already described here with the `isnull` filter after upgrading to 2.6. Has it really been fixed?

**Comment by martasd** [comment]
I take this back. I do not see the issue anymore. Thanks for fixing!
